### ISSUE TITLE
Building examples without IAR or CCS

### ISSUE THREAD

**Issue by albertogara** [TexasInstruments/simplelink-ti154stack-examples#1]
It is possible to build the SDK repository without IAR or CCS IDEs as described here:
https://github.com/TexasInstruments/simplelink-lowpower-f2-sdk

However, instructions to compile the examples are only given for IAR and CCS.
Can I compile the examples with my GNU arm toolchain?

I wish the documentation were more specific about this. Can anybody provide any assistance for this?

**Comment by cringti** [comment]
This specific repo contains TI's 15.4 stack examples.  GCC examples are not provided for the 15.4 stack as that stack currently doesn't support GCC(!).  You can get a hint of this by inspecting the pre-built 15.4 libraries, they are [currently only provided for TI Clang and IAR](https://github.com/TexasInstruments/simplelink-lowpower-f2-sdk/tree/lpf2-7.41.00.17/source/ti/ti154stack/lib).

We will look for ways to improve the documentation to make it clearer when a stack only supports a subset of the toolchains that the larger SDK supports.
